### ISSUE TITLE
Белый экран при смене папки контрактов

### ISSUE THREAD

**Issue by zinyakov** [alfa-laboratory/thrift-api-ui#2]
иногда такое бывает, что с подключенным туннелем меняешь папку с контрактами через настройки - и приложение намертво виснет на белом экране и не отзывается на вызов настроек. 
Переустановка не помогает, помогает только удаление папки  ~/Library/Application Support/Thrift Api UI/

**Comment by Heymdall** [comment]
@zinyakov попробуй эту версию:
https://github.com/alfa-laboratory/thrift-api-ui/releases/tag/v2.2.0

**Comment by zinyakov** [comment]
да, вроде сейчас нормально все, спасибо
