### ISSUE TITLE
Отображение версии приложения

### ISSUE THREAD

**Issue by y-fedorov** [alfa-laboratory/thrift-api-ui#7]
Было-бы круто иметь возможность просмотреть текущую версию в приложении.

(Возможно это есть и я не нашёл)

Версия: v2.4.0

**Comment by stepancar** [comment]
@y-fedorov implemented, but new version not published yet

**Comment by Luchanso** [comment]
Fixed in release [v2.5.0](https://github.com/alfa-laboratory/thrift-api-ui/releases/tag/2.5.0)
